/**
 * The ten real photographs on the ABC School recovery board.
 *
 * These are NOT fetched at runtime. `scripts/fetchItemPhotos.js` is a one-off
 * sourcing tool (Wikimedia Commons API + a licensed-source review); the curated
 * output is vendored into `uploads/items/photo/` so the demo renders offline and
 * identically on every machine, exactly like the drawn SVG artwork.
 *
 * `credits.json` next to the images is generated by the sourcing tool and holds
 * the author and licence for each file, which ATTRIBUTION.md points at.
 *
 * Every entry is an explicit slug -> file mapping. There is deliberately no
 * "slugify the item name" fallback: a silent miss would put a broken image, or
 * worse the wrong product, next to a name.
 */
const PHOTO_BY_ITEM = {
  'Black Handbag': 'black-handbag',
  'Blue Tablet': 'blue-tablet',
  'Silver Watch': 'silver-watch',
  'Black Headphones': 'black-headphones',
  'Black Sunglasses': 'black-sunglasses',
  'Teal Water Bottle': 'teal-water-bottle',
  'Navy Track Pants': 'navy-track-pants',
  'Silver Laptop Stand': 'silver-laptop-stand',
  'Grey Wireless Mouse': 'grey-wireless-mouse',
  'Student ID Card': 'student-id-card'
};

/** '/uploads/items/photo/silver-watch.jpg' for 'Silver Watch', else null. */
function photoFor(itemName) {
  const slug = PHOTO_BY_ITEM[itemName];
  return slug ? [`/uploads/items/photo/${slug}.jpg`] : null;
}

const SLUGS = Object.values(PHOTO_BY_ITEM);

module.exports = { PHOTO_BY_ITEM, photoFor, SLUGS };
